version: '3'
services:
  fastbot-ros2-gazebo:
    image: kuralme/kuralme-cp22:fastbot-ros2-real
    container_name: fastbot-ros2-real
    environment:
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=/var/lib/theconstruct.rrl/cyclonedds.xml
    volumes:
      - /dev/video0:/dev/video0
      - /dev/lslidar:/dev/lslidar
      - /dev/arduino_nano:/dev/arduino_nano
      - ./ros_entrypoint.sh:/ros_entrypoint.sh
      - /var/lib/theconstruct.rrl/cyclonedds.xml:/var/lib/theconstruct.rrl/cyclonedds.xml
    privileged: true
    network_mode: host
    restart: always
    entrypoint: /ros_entrypoint.sh
    command: ["ros2 launch fastbot_bringup bringup.launch.xml"]
  
  fastbot-ros2-slam:
    image: kuralme/kuralme-cp22:fastbot-ros2-real-slam
    container_name: fastbot-ros2-real-slam
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=/var/lib/theconstruct.rrl/cyclonedds.xml
    volumes:
      - ./ros_entrypoint.sh:/ros_entrypoint.sh
      - /var/lib/theconstruct.rrl/cyclonedds.xml:/var/lib/theconstruct.rrl/cyclonedds.xml
      - /tmp/.X11-unix:/tmp/.X11-unix
    privileged: true
    network_mode: host
    restart: always
    entrypoint: /ros_entrypoint.sh
    command: ["sleep 8 && ros2 launch fastbot_slam navigation.launch.py"]