FROM ros:humble-ros-base-jammy

SHELL [ "/bin/bash" , "-c" ]

# Install system and ROS 2 dependencies
RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    python3-colcon-common-extensions \
    python3-pip \
    python3-setuptools \
    build-essential \
    lsb-release \
    libboost-all-dev \
    libpcap-dev \
    libpcl-dev \
    ros-humble-xacro \
    ros-humble-tf2* \
    ros-humble-joint-state-publisher \
    ros-humble-pcl-conversions \
    ros-humble-pluginlib \
    ros-humble-diagnostic-updater \
    ros-humble-v4l2-camera \
    ros-humble-image-transport-plugins \
    v4l-utils \
    && rm -rf /var/lib/apt/lists/*

# Install motor driver dependencies
RUN python3 -m pip install pyserial

# Create ROS2 workspace
RUN mkdir -p /colcon_ws/src
COPY ./fastbot /colcon_ws/src/fastbot
RUN source /opt/ros/humble/setup.bash && cd /colcon_ws && colcon build --symlink-install

WORKDIR /colcon_ws