version: '3'
services:
  fastbot-ros2-gazebo:
    image: kuralme/kuralme-cp22:fastbot-ros2-real
    container_name: fastbot-ros2-real
    environment:
      - ROS_DOMAIN_ID=0
    devices:
      - /dev/video0
      - /dev/lslidar
      - /dev/arduino_nano
    privileged: true
    networks:
      - fastbot-network
    restart: always
    entrypoint: ["/bin/bash", "-c"]
    command: ["source install/setup.bash && ros2 launch fastbot_bringup bringup.launch.xml"]
  
  fastbot-ros2-slam:
    image: kuralme/kuralme-cp22:fastbot-ros2-real-slam
    container_name: fastbot-ros2-real-slam
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    privileged: true
    networks:
      - fastbot-network
    restart: always
    entrypoint: ["/bin/bash", "-c"]
    command: ["sleep 8 && source install/setup.bash && ros2 launch fastbot_slam navigation.launch.py"]

networks:
  fastbot-network:
    driver: bridge