version: '3'
services:
  fastbot-ros2-gazebo:
    image: kuralme/kuralme-cp22:fastbot-ros2-gazebo
    container_name: fastbot-ros2-gazebo
    environment:
      - DISPLAY=${DISPLAY}
      # - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      # - CYCLONEDDS_URI=/var/lib/theconstruct.rrl/cyclonedds.xml
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    networks:
      - fastbot-network
    restart: always
    entrypoint: ["/bin/bash", "-c", "source install/setup.bash && ros2 launch fastbot_gazebo one_fastbot_room.launch.py"]
  
  fastbot-ros2-slam:
    image: kuralme/kuralme-cp22:fastbot-ros2-slam
    container_name: fastbot-ros2-slam
    environment:
      - DISPLAY=${DISPLAY}
      # - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      # - CYCLONEDDS_URI=/var/lib/theconstruct.rrl/cyclonedds.xml
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    networks:
      - fastbot-network
    restart: always
    entrypoint: ["/bin/bash", "-c", "source install/setup.bash && ros2 launch fastbot_slam navigation.launch.py"]
    
  # fastbot-ros2-webapp:
  #   image: kuralme/kuralme-cp22:fastbot-ros2-webapp
  #   container_name: fastbot-ros2-webapp
  #   network_mode: host
  #   environment:
  #     - DISPLAY=${DISPLAY}
  #     - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
  #     - CYCLONEDDS_URI=/var/lib/theconstruct.rrl/cyclonedds.xml
  #   volumes:
  #     - /tmp/.X11-unix:/tmp/.X11-unix
  #   networks:
  #     - fastbot-network
  #   restart: always
  #   entrypoint: ["/bin/bash", "-c", "python3 -m http.server 7000 && ros2 launch rosbridge_server rosbridge_websocket_launch.xml"]

networks:
  fastbot-network:
    driver: bridge